defaults:
  - default

_target_: otx.core.model.module.OTXActionLitModule

otx_model:
  _target_: otx.core.model.entity.action.MMActionCompatibleModel
  config: ???

# compile model for faster training with pytorch 2.0
torch_compile: false
